Repository nimi1125/blog-app, pull requests merged in 2024-11, with the labels that each got.

#33 Feature/blog020
  app/Http/Controllers/PostController.php
  app/Models/Category.php
  app/Models/Post.php
  app/Models/User.php
  resources/views/blog/write.blade.php
  resources/views/layouts/write.blade.php
  routes/web.php
Labels: writeblog

#34 postbox.blade.phpのレイアウトを調整しました
  app/Http/Controllers/PostController.php
  resources/views/layouts/postbox.blade.php
  routes/web.php
Labels: home

#36 post一覧のデータ取得処理を追加しました
  app/Http/Controllers/PostController.php
  resources/views/layouts/postbox.blade.php
  routes/web.php
Labels: home

#37 homeのページネーションを追加しました
  app/Http/Controllers/PostController.php
  resources/css/style.css
  resources/views/layouts/postbox.blade.php
Labels: home

#35 Feature/blog032
  app/Http/Controllers/PostController.php
  app/Http/Requests/PostRequest.php
  resources/views/blog/write.blade.php
  routes/web.php
Labels: writeblog

#39 Feature/blog021
  resources/css/style.css
  resources/views/blog/write.blade.php
Labels: writeblog

#40 Feature/blog016
  app/Http/Controllers/PostController.php
  public/img/person.jpg
  resources/views/blog/detail.blade.php
  resources/views/layouts/detail.blade.php
  routes/web.php
Labels: blogview

#41 Feature/blog015
  app/Http/Controllers/PostController.php
  resources/views/blog/detail.blade.php
Labels: blogview

#42 your post一覧のデータ取得処理を追加しました
  app/Http/Controllers/PostController.php
  app/Providers/RouteServiceProvider.php
  resources/views/home.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/mypage.blade.php
  routes/web.php
Labels: Profile

#43 your post一覧のページネーションとヘッダーを編集しました
  app/Http/Controllers/PostController.php
  app/Models/Post.php
  database/seeders/PostsTableSeeder.php
  resources/views/home.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/layouts/postbox.blade.php
  resources/views/layouts/search.blade.php
  resources/views/mypage.blade.php
  routes/web.php
Labels: Profile

#45 comment投稿機能追加 #17
  app/Http/Controllers/CommentController.php
  app/Models/Comment.php
  resources/views/blog/detail.blade.php
  routes/web.php
Labels: blogview

#46 feature/blog014メント表示調整
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/PostController.php
  app/Models/Comment.php
  resources/css/style.css
  resources/views/blog/detail.blade.php
Labels: blogview

#48 feature/blog013コメントバリデーション追加
  app/Http/Controllers/CommentController.php
  app/Http/Requests/CommentRequest.php
  resources/views/blog/detail.blade.php
Labels: blogview

#47 post検索機能を実装しました
  app/Http/Controllers/PostController.php
  resources/views/layouts/navigation.blade.php
  resources/views/layouts/postbox.blade.php
  resources/views/layouts/search.blade.php
Labels: home

#57 コメントしたら違う詳細ページに飛ぶため修正(リダイレクト先がおかしい。)
  app/Models/Comment.php
  app/Models/Post.php
  resources/views/blog/detail.blade.php
Labels: blogview

#61 投稿された画像がpublic/imgに保存されるように調整しました
  app/Http/Controllers/PostController.php
Labels: writeblog
